<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_request_vaccine_tests.MyTestCase-20220318013022" tests="19" file="test_request_vaccine_tests.py" time="0.125" timestamp="2022-03-18T01:30:23" failures="1" errors="0" skipped="0">
	<testcase classname="test_request_vaccine_tests.MyTestCase" name="test_comprobarhash" time="0.078" timestamp="2022-03-18T01:30:23"/>
	<testcase classname="test_request_vaccine_tests.MyTestCase" name="test_edad_inferior" time="0.000" timestamp="2022-03-18T01:30:23"/>
	<testcase classname="test_request_vaccine_tests.MyTestCase" name="test_edad_no_numero" time="0.000" timestamp="2022-03-18T01:30:23"/>
	<testcase classname="test_request_vaccine_tests.MyTestCase" name="test_edad_superior" time="0.016" timestamp="2022-03-18T01:30:23"/>
	<testcase classname="test_request_vaccine_tests.MyTestCase" name="test_guardado_correcto_json" time="0.000" timestamp="2022-03-18T01:30:23"/>
	<testcase classname="test_request_vaccine_tests.MyTestCase" name="test_hash_es_str" time="0.016" timestamp="2022-03-18T01:30:23"/>
	<testcase classname="test_request_vaccine_tests.MyTestCase" name="test_nombre_largo" time="0.000" timestamp="2022-03-18T01:30:23"/>
	<testcase classname="test_request_vaccine_tests.MyTestCase" name="test_nombre_sin_apellido" time="0.000" timestamp="2022-03-18T01:30:23"/>
	<testcase classname="test_request_vaccine_tests.MyTestCase" name="test_nombre_vacio" time="0.000" timestamp="2022-03-18T01:30:23"/>
	<testcase classname="test_request_vaccine_tests.MyTestCase" name="test_numerotelef_muycorto" time="0.000" timestamp="2022-03-18T01:30:23"/>
	<testcase classname="test_request_vaccine_tests.MyTestCase" name="test_numerotelef_muylargo" time="0.000" timestamp="2022-03-18T01:30:23"/>
	<testcase classname="test_request_vaccine_tests.MyTestCase" name="test_numerotelef_nonumero" time="0.000" timestamp="2022-03-18T01:30:23"/>
	<testcase classname="test_request_vaccine_tests.MyTestCase" name="test_patientID_incorrecto" time="0.000" timestamp="2022-03-18T01:30:23"/>
	<testcase classname="test_request_vaccine_tests.MyTestCase" name="test_tamanocorrectohash" time="0.000" timestamp="2022-03-18T01:30:23"/>
	<testcase classname="test_request_vaccine_tests.MyTestCase" name="test_tiporegistro_nostr" time="0.000" timestamp="2022-03-18T01:30:23"/>
	<testcase classname="test_request_vaccine_tests.MyTestCase" name="test_tiporegistro_novalido" time="0.000" timestamp="2022-03-18T01:30:23"/>
	<testcase classname="test_request_vaccine_tests.MyTestCase" name="test_uuid_correcta" time="0.000" timestamp="2022-03-18T01:30:23"/>
	<testcase classname="test_request_vaccine_tests.MyTestCase" name="test_uuid_incorrecta" time="0.000" timestamp="2022-03-18T01:30:23"/>
	<testcase classname="test_request_vaccine_tests.MyTestCase" name="test_registro_correcto" time="0.016" timestamp="2022-03-18T01:30:23">
		<failure type="AssertionError" message="'66cde421a6194e70e283cc39c537721f' != '0f2cf46c635846fa4cea097070061279'
- 66cde421a6194e70e283cc39c537721f
+ 0f2cf46c635846fa4cea097070061279
"><![CDATA[Traceback (most recent call last):
  File "C:\Users\talib\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\talib\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "C:\Users\talib\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 550, in _callTestMethod
    method()
  File "c:\users\talib\desktop\g81.2022.15.e3\venv\lib\site-packages\freezegun\api.py", line 789, in wrapper
    result = func(*args, **kwargs)
  File "c:\users\talib\desktop\g81.2022.15.e3\src\unittest\python\test_request_vaccine_tests.py", line 107, in test_registro_correcto
    self.assertEqual(patient_id_test, hashlib.md5(json.dumps(patient).encode("utf-8")).hexdigest())
  File "C:\Users\talib\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\talib\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 1209, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\talib\AppData\Local\Programs\Python\Python39\lib\unittest\case.py", line 668, in fail
    raise self.failureException(msg)
AssertionError: '66cde421a6194e70e283cc39c537721f' != '0f2cf46c635846fa4cea097070061279'
- 66cde421a6194e70e283cc39c537721f
+ 0f2cf46c635846fa4cea097070061279

]]></failure>
	</testcase>
</testsuite>
